spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/aamvdb

application:
  jwt:
    secretKey: ${secretkey:securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure}
    tokenExpirationAfterHours: ${tokenExpirationAfterHours:4}